### ISSUE TITLE
Debug.py Object passing in non class python file?

### ISSUE THREAD

**Issue by OpenSourceIronman** [ROBO-BEV/Tapomatic#8]
How do I pass the Debug() object (first line of code in main function of Driver.py) to functions not in a python class without adding it to every function parameter list?

**Comment by OpenSourceIronman** [comment]
For example Ping.py I converted RaspPi.py to a class so this issue is less of a worry now. I would still like to know the best practice for passing objects tho :)

**Comment by dull7295** [comment]
How to pass an object to a function not defined within the class?
